baseline_program: P_OGI
end_date:
- 2021
- 12
- 31
input_directory: ./inputs
make_plots: true
n_processes: null
n_simulations: 10
output_directory: ./outputs
parameter_level: global
pregenerate_leaks: false
preseed_random: false
print_from_simulations: true
programs:
  P_OGI:
    NRd: 365
    consider_weather: false
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
        - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    emissions:
      LPR: 0.0065
      consider_venting: false
      leak_dist_params:
      - -2.776
      - 1.462
      leak_dist_type: lognorm
      leak_file: null
      leak_file_use: sample
      max_leak_rate: 100000.0
      subtype_leak_dist_file: null
      units:
      - kilogram
      - hour
      vent_file: site_rates.csv
    end_date:
    - 2021
    - 12
    - 31
    infrastructure_file: facility_list_template.csv
    method_labels:
    - OGI
    methods:
      OGI:
        RS: 6
        consider_daylight: false
        cost:
          per_day: 0
          per_hour: 0
          per_site: 600
          upfront: 0
        coverage:
          spatial: 0.9
          temporal: 0.9
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: false
        label: OGI
        max_workday: 8
        measurement_scale: component
        n_crews: null
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
          - -114.062
          - 51.044
          deployment_months: []
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
          - 0.0362
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
          - 30
        time: 120
        version: '2.0'
        weather_envs:
          precip:
          - 0.0
          - 0.5
          temp:
          - -40.0
          - 40.0
          wind:
          - 0.0
          - 10.0
    parameter_level: program
    program_name: P_OGI
    repair_delay: 14
    site_samples: 500
    start_date:
    - 2017
    - 1
    - 1
    subtype_times_file: null
    version: '2.0'
    weather_file: ERA5_AB_lowres_2015_2020.nc
    weather_is_hourly: false
reference_program: P_OGI
start_date:
- 2017
- 1
- 1
version: '2.0'
write_data: true
