parameter_level: method
version: '2.0'
label: operator
deployment_type: stationary
measurement_scale: component
is_follow_up: False
sensor: 
  type: default
  MDL: [10]
coverage:
  spatial: 0.5
  temporal: 0.5