parameter_level: method
label: aircraft
deployment_type: mobile
measurement_scale: equipment
is_follow_up: False
sensor: 
  type: default
  MDL: [1.5]
cost:
  per_site: 200
coverage:
  spatial: 0.9
  temporal: 0.9
t_bw_sites:
  vals: [5]
RS: 2
time: 1
