parameter_level: method
version: '2.0'
label: operator
deployment_type: stationary
measurement_scale: component

is_follow_up: False
reporting_delay: 2
consider_daylight: False
cost:
  per_day: 0
  per_site: 0
  per_hour: 0
  upfront: 100000
coverage:
  spatial: 0.01
  temporal: 1.0
follow_up:
  delay: 0
  instant_threshold: '_placeholder_float_'
  instant_threshold_type: 'absolute'
  interaction_priority: 'threshold'
  proportion: 1.0
  redundancy_filter: 'recent'
  threshold: 0.0
  threshold_type: 'absolute'
max_workday: 8
n_crews: 1
scheduling:
  deployment_months: ['_placeholder_int_']
  deployment_years: ['_placeholder_int_']
  LDAR_crew_init_location: [-114.062, 51.044]
  home_bases_files: 'Airport_AB_Coordinates.csv'
  route_planning: False
  travel_speeds: ['_placeholder_int_']
sensor:
  type: default
  QE: 0.0
  MDL: [0.10]
t_bw_sites:
  file: '_placeholder_str_'
  vals: [30]
weather_envs:
  precip: [0.0, 0.5]
  temp: [-30.0, 40.0]
  wind: [0.0, 10.0] 
