parameter_level: method
version: '2.0'
label: satellite
consider_daylight: True
deployment_type: orbit
measurement_scale: equipment
sensor: 
  type: default
  MDL: [0.5]
is_follow_up: True
cost:
  per_day: 0
  per_site: 500
  upfront: 0
follow_up:
  threshold: 0.0
reporting_delay: 2
sensor:
  type: Satellite
  MDL: [5.79,1.39]
t_bw_sites:
  vals: [5]
TLE_label: GHGSAT-D
TLE_file: Sat_TLEs.txt
