parameter_level: method
label: stationary
deployment_type: stationary
measurement_scale: equipment
is_follow_up: False
sensor: 
  type: default
  MDL: [0.5]
cost:
  per_day: 1
  upfront: 500
coverage:
  spatial: 0.9
  temporal: 0.12
