parameter_level: method
label: truck
deployment_type: mobile
measurement_scale: equipment
is_follow_up: False
sensor: 
  type: default
  MDL: [0.01]
cost:
  per_site: 400
coverage:
  spatial: 0.7
  temporal: 0.8
t_bw_sites: 
  vals: [30]
RS: 2
time: 30