baseline_program: P_none
end_date:
- 2021
- 12
- 31
input_directory: ./inputs
make_plots: true
n_processes: null
n_simulations: 10
output_directory: ./outputs
parameter_level: global
pregenerate_leaks: false
preseed_random: false
print_from_simulations: true
programs:
  P_none:
    NRd: 365
    consider_weather: false
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
        - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    emissions:
      LPR: 0.0065
      consider_venting: false
      leak_dist_params:
      - -2.776
      - 1.462
      leak_dist_type: lognorm
      leak_file: null
      leak_file_use: sample
      max_leak_rate: 100000.0
      subtype_leak_dist_file: null
      units:
      - kilogram
      - hour
      vent_file: site_rates.csv
    end_date:
    - 2021
    - 12
    - 31
    infrastructure_file: facility_list_template.csv
    method_labels: []
    methods: {}
    parameter_level: program
    program_name: P_none
    repair_delay: 14
    site_samples: 500
    start_date:
    - 2017
    - 1
    - 1
    subtype_times_file: null
    version: '2.0'
    weather_file: ERA5_AB_lowres_2015_2020.nc
    weather_is_hourly: false
reference_program: P_none
start_date:
- 2017
- 1
- 1
version: '2.0'
write_data: true
