parameter_level: method
version: '2.0'
label: drone
deployment_type: mobile
measurement_scale: equipment
is_follow_up: False
sensor: 
  type: default
  MDL: [0.01]
cost:
  per_site: 500
coverage:
  spatial: 1.0
  temporal: 0.9
t_bw_sites: 
  vals: [30]
RS: 2
time: 20