parameter_level: method
version: '2.0'
label: satellite
deployment_type: orbit
measurement_scale: site
sensor: 
  type: satellite
  MDL: [5.79, 1.39]
is_follow_up: False
cost:
  per_day: 100
TLE_label: default
TLE_file: Sat_TLEs.txt
